apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: weather-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.9.2
          ports:
            - containerPort: 3100
              name: http-metrics
          volumeMounts:
            - name: loki-data
              mountPath: /loki
          resources:
            limits:
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
      volumes:
        - name: loki-data
          persistentVolumeClaim:
            claimName: loki-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
  namespace: weather-ops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: weather-ops
spec:
  ports:
    - port: 3100
      targetPort: 3100
      name: http-metrics
  selector:
    app: loki