version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./data:/app/data
    networks:
      - weather_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "8502:8501"
    environment:
      - BACKEND_URL=http://backend:5000
    volumes:
      - ./data:/app/data
    depends_on:
      - backend
    networks:
      - weather_network
    restart: unless-stopped

networks:
  weather_network:
    driver: bridge