apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: weather-ops
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
      - job_name: 'weather-ops-backend'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - weather-ops
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: backend
          - source_labels: [__meta_kubernetes_pod_container_port_name]
            action: keep
            regex: .*
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            regex: .*
            action: keep
        metrics_path: /metrics
        scheme: http
      
      # Static config as a fallback to ensure we're scraping the backend
      - job_name: 'weather-ops-backend-static'
        static_configs:
          - targets: ['backend.weather-ops.svc.cluster.local:5000']
        metrics_path: /metrics
      
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/${1}/proxy/metrics