apiVersion: apps/v1
kind: Deployment

metadata:
  name: grafana
  namespace: weather-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:10.2.0
          ports:
            - containerPort: 3000
              name: http-grafana
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "WeatherOps2025Secure!"
            - name: GF_INSTALL_PLUGINS
              value: "grafana-piechart-panel"
            - name: GF_DASHBOARDS_MIN_REFRESH_INTERVAL
              value: "5s"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: "Viewer"
          volumeMounts:
            - name: grafana-config
              mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
              subPath: datasources.yaml
            - name: grafana-dashboards-config
              mountPath: /etc/grafana/provisioning/dashboards/dashboards.yaml
              subPath: dashboard-provider.yaml
            - name: weather-ops-logs-dashboard
              mountPath: /var/lib/grafana/dashboards/weather-ops-logs-dashboard.json
              subPath: weather-ops-logs-dashboard.json
            - name: grafana-storage
              mountPath: /var/lib/grafana
          resources:
            limits:
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
      volumes:
        - name: grafana-config
          configMap:
            name: grafana-datasources
        - name: grafana-dashboards-config
          configMap:
            name: grafana-dashboards
        - name: weather-ops-logs-dashboard
          configMap:
            name: weather-ops-logs-dashboard
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pvc
