apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: weather-ops
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080
    protocol: TCP