apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: weather-ops
  labels:
    app: grafana
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30300
      protocol: TCP
      name: http-grafana
  selector:
    app: grafana